### PR TITLE
upgrading to SoapUI 5.1.2

### PR DESCRIPTION
**Pull request by SiKing**
Build against SoapUI 5.1.2.
Sorry about the huge white-space reformat of the pom - I blame Eclipse. :)

### CODE REVIEW

**Comment by pbielicki** [comment]
Hi,

Thx for PR.

Please align your formatting to the one used by me i.e. 2 spaces instead of tab (or 4 spaces).

Is your change backward compatible? If not I will create a separate branch for each major version.

Cheers,
PB

**Comment by SiKing** [comment]
I fixed the spacing. Do I have to create a new pull request?

I am pretty sure it will not be downwards compatible, due to the new method in WebSocketRequestTransport.java.

**Comment by pbielicki** [comment]
Yes, please cancel this pr and create a new one targetting releases/5.x branch

Many thanks

**Comment by SiKing** [comment]
I think this closes the request?

**Pull request closed without merging**
